# criando um banco de dados postgresql chamado gnclima


services:
  db:
    image: postgres:15
    container_name: gnclima_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: gnclima
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: gnclima_api
    restart: always
    depends_on:
      - db
    environment:
      OPENWEATHER_KEY: ${OPENWEATHER_KEY}
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres123
      DB_NAME: gnclima
    ports:
      - "3001:3001"

volumes:
  pgdata:

